### PR TITLE
Add input variables `commit` and `title`

### PR DESCRIPTION
**Pull request by ocavue**
This PR add an option to change the commit message prefix, which is `ci(changest)` by default.

### CODE REVIEW

**Comment by ocavue** [comment]
Currently, the commit message is a dynamic string based on `isInPreMode` and `preState.tag`. Are you going to change this into a static string `Version Packages`?

**Comment by ocavue** [comment]
In fact, there is two things we can add configuration to: `prTitle` and `commitMsg`

```javascript
const prTitle = `Version Packages${isInPreMode ? ` (${preState.tag})` : ""}`;
const commitMsg = `ci(changeset): generate PR with changelog &${isInPreMode ? ` (${preState.tag})` : ""} version updates`;
```

For both two strings, we can add the `preState.tag` part at the end of string. For example:

```javascript
const prTitle = inputs.prTitle + (isInPreMode ? ` (${preState.tag})` : "");
const commitMsg = inputs.commit + (isInPreMode ? ` (${preState.tag})` : "");
```

What do you think of this idea?

**Comment by mitchellhamilton** [comment]
That looks fine though could you make the default commit message `Version Packages` (no prefix)?

**Comment by ocavue** [comment]
> could you make the default commit message Version Packages (no prefix)?

@mitchellhamilton done.

**Comment by ocavue** [comment]
You're welcome.

**Pull request merged**
