### PR TITLE
Resolve @changesets/cli with resolve-from

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This switches `run.ts` from assuming the `node_modules` directory location to using `require.resolve` under the hood to locate the real location of `@changesets/cli`. 

It uses the [resolve-from](https://github.com/sindresorhus/resolve-from) module to do the resolving from the current directory, otherwise just a plain `require.resolve` would attempt to locate the `@changesets/cli` nearest to `run.ts`, rather than the user's project.

As mentioned by @merceyz in https://github.com/changesets/action/issues/66#issuecomment-763501827, you can pair this with `NODE_OPTIONS="-r <cwd>./.pnp.(c)js"` to enable support for Yarn 2 / PnP.

Related to #66

### CODE REVIEW

**Comment by merceyz** [comment]
> It uses the resolve-from module to do the resolving from the current directory, otherwise just a plain require.resolve would attempt to locate the @changesets/cli nearest to run.ts, rather than the user's project.

You can use the `paths` option, no need to grab a npm package for this
https://nodejs.org/api/modules.html#modules_require_resolve_request_options

**Comment by jacobwgillespie** [comment]
> You can use the `paths` option as I mentioned in [#66 (comment)](https://github.com/changesets/action/issues/66#issuecomment-763501827), no need to grab a npm package for this
> [nodejs.org/api/modules.html#modules_require_resolve_request_options](https://nodejs.org/api/modules.html#modules_require_resolve_request_options)

Unless I'm misunderstanding, it's not _quite_ that simple, as `paths` entirely replaces the default resolution logic's lookup directories, so specifying `paths: [cwd]` would only allow the module to be present at `$PWD/node_modules/x`, but `$PWD/../node_modules/x` would not resolve, etc.

There's a way to build a list of directories that should be checked and pass that into `paths`, as well as a few edge-cases around resolving directory symlinks to handle, but that that point you've ended up recreating the body of `resolve-from`, minus the tests: https://github.com/sindresorhus/resolve-from/blob/main/index.js

**Comment by merceyz** [comment]
> Unless I'm misunderstanding, it's not quite that simple, as paths entirely replaces the default resolution logic's lookup directories, so specifying paths: [cwd] would only allow the module to be present at $PWD/node_modules/x, but $PWD/../node_modules/x would not resolve, etc.

As the docs specify `paths` is where it should start seaching, parent folders are also checked

> Each of these paths is used as a starting point for the module resolution algorithm, meaning that the node_modules hierarchy is checked from this location.

**Comment by jacobwgillespie** [comment]
> As the docs specify `paths` is where it should **start** searching so parent folders are also checked

Oh nice, yes I was indeed misunderstanding. I've updated to use `require.resolve` directly 👍

**Comment by Andarist** [comment]
> As mentioned by @merceyz in #66 (comment), you can pair this with NODE_OPTIONS="-r <cwd>./.pnp.(c)js" to enable support for Yarn 2 / PnP.

Is this worth documenting?

**Comment by jacobwgillespie** [comment]
> Is this worth documenting?

Probably yeah, I updated the PR with a README section. The `.pnp.js` file needs to be required with an absolute path, not a relative path, to ensure it's resolved even when scripts are run from subdirectories, so it's likely good to have a README example.

**Review by Andarist — APPROVED** [review]
I will let it sit for a couple of days - maybe someone else would like to take a look at this before merging as well. If no one will I will merge this soon(-ish) - in case I forget about it feel free to ping me.

**Review by merceyz — APPROVED** [review]
LGTM - Might want to update the title and description though

**Comment by jacobwgillespie** [comment]
Okay, pinging @Andarist, this is still working for us (feel free to wait longer if you'd like, just following up on the reminder request).

**Review by mitchellhamilton — COMMENTED** [review]
tbh, wouldn't it be easier to tell people to do this instead (the code change seems fine but for the documentation, the below seems easier)

```yaml
with:
  version: yarn changeset version
```

**Comment by jacobwgillespie** [comment]
> wouldn't it be easier to tell people to do this instead

Yep, that does seem simpler - I've updated the PR to recommend a custom version command ✅

**Comment by jacobwgillespie** [comment]
This PR breaks the action for non-Yarn-2 projects it seems - I've opened PR #71 to fix.

**Pull request merged**
