### PR TITLE
Feature: Allow custom `branch`

### PR DESCRIPTION
**Pull request by ernestognw**
Solves #254

### CODE REVIEW

**Review by antoinekm — APPROVED** [review]

**Comment by bgfernandes** [comment]
Hey all, can we merge this?

**Comment by AntoineKM** [comment]
hey @Andarist or @emmatown can you take a look on this pr it should be very quick.

**Comment by bgfernandes** [comment]
Any updates on this?

**Comment by tompahoward** [comment]
yes please. I need this too

**Comment by peersky** [comment]
+1 Also need that :)

**Review by emmatown — APPROVED** [review]

**Comment by tompahoward** [comment]
Thank you @emmatown 🙏

**Comment by ernestognw** [comment]
omg guys I love you

**Review by Frank122480 — COMMENTED** [review]
Good with it

**Pull request merged**
